name: Build TrypPM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Trypillia
        uses: trypillia/setup-trypillia@v2
        with:
          version: 'latest'

      - name: Build TrypPM binary
        run: trypillia build main.try tryppm

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v7
        with:
          name: tryppm-linux-amd64
          path: tryppm
          retention-days: 7
