name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Trypillia
        uses: trypillia/setup-trypillia@v2
        with:
          version: 'latest'

      - name: Upload Trypillia Binaries
        uses: actions/upload-artifact@v4
        with:
          name: trypillia-binaries
          path: ~/.local/bin/trypillia*
          retention-days: 1

      - name: Run Tests
        run: trypillia-test --coverage test.try

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7
        with:
          files: ./coverage.info

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Download Trypillia Binaries
        uses: actions/download-artifact@v4
        with:
          name: trypillia-binaries
          path: ~/.local/bin/

      - name: Setup Trypillia (From Artifact)
        run: |
          chmod +x ~/.local/bin/trypillia*
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build TrypPM binary
        run: trypillia build main.try tryppm

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tryppm-linux-amd64
          path: tryppm
          retention-days: 7
